version: '3.3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'library'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'libraryroot'
      # You can use whatever password you like
      MYSQL_PASSWORD: '161ebd7d45089b3446ee4e0d86dbcf92'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '161ebd7d45089b3446ee4e0d86dbcf92'
    ports:
      - "3306:3306"
  web:
    image: web:latest
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
  backend:
    image: backend:latest
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      IP: http://localhost:3000
      PORT: 3000
      DATABASE_FRONT: library
      HOST: db
      USERNAME_FRONT: libraryroot
      PASSWORD_FRONT: 161ebd7d45089b3446ee4e0d86dbcf92
    ports:
      - "3000:3000"
